version: '3.8'

services:
  boilerplate_db:
    image: postgres:12.0-alpine
    container_name: boilerplate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_database_dev

  boilerplate_front:
    image: boilerplate/django
    container_name: boilerplate_front
    command: yarn serve
    volumes:
      - ./:/usr/src/app

  boilerplate_app:
    build: ./
    image: boilerplate/django
    container_name: boilerplate_app
    command: python manage.py runserver --settings=conf.settings.development 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - boilerplate_db
      - boilerplate_front

volumes:
  postgres_data:
